# Generated by Django 2.2.7 on 2019-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='data happened')),
                ('user_id', models.CharField(max_length=16)),
                ('content_id', models.CharField(max_length=16)),
                ('event', models.CharField(max_length=200)),
                ('session_id', models.CharField(max_length=128)),
            ],
        ),
    ]
